app01/urls.py
from django.conf.urls import url
from app01 import views

urlpatterns = [
    # 展示出版社
    url(r'^publisher_list/$',views.publisher_list,name='publisher'),
    # 增加出版社
    url(r'^publisher_add/$',views.PublisherAdd.as_view(),name='pub_add'),
    # 删除出版社
    # url(r'^publisher_del/(\d+)/$',views.publisher_del,name='pub_del'),   # 将要删除的出版社id通过位置参数传递给视图函数publisher_del
    # 编辑出版社
    url(r'^publisher_edit/(?P<id>\d+)/$',views.publisher_edit,name='pub_edit'),   # 将要编辑的出版社id通过关键字参数传递给视图函数publisher_edit

    # 查看所有的图书
    url(r'^book_list/$',views.book_list,name='book'),

    # 添加图书
    url(r'^book_add/$',views.BookAdd.as_view(),name='book_add'),

    # 编辑图书
    url(r'^book/edit/(\d+)/',views.BookEdit.as_view(),name='book_edit'),

    # 删除图书
    # url(r'^book/del/(?P<pk>\d+)',views.book_del,name='book_del'),

    # 删除出版社和删除图书的逻辑一样，将url进行合并
    url(r'^(\w+)/del/(\d+)/',views.delete,name='del'),     # 按照位置参数传递给视图函数

    # 作者展示
    url(r'^author/$',views.author_list,name='author'),

    # 添加作者
    url(r'^author/add/$',views.author_add,name='author_add'),

    # 编辑
    url(r'^author/edit/(\d+)',views.author_edit,name='author_edit'),

]

bookmanager/urls.py
from django.conf.urls import url,include
from django.contrib import admin
# from app01 import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    # 路由分发,同时定义namespace
    url(r'^app01/',include('app01.urls',namespace='app01')),
    # # 展示出版社
    # url(r'^publisher_list/',views.publisher_list),
    # # 增加出版社
    # url(r'^publisher_add/',views.publisher_add),
    # # 删除出版社
    # url(r'^publisher_del/',views.publisher_del),
    # # 编辑出版社
    # url(r'^publisher_edit/',views.publisher_edit),
]

templates/author.html
{% extends 'base.html' %}

{% block title %}
   author
{% endblock %}

{% block author_active %}
    active
{% endblock %}

{% block content %}

          <h2 class="sub-header">作者列表</h2>
            <a class="btn btn-info btn-default" href={% url 'app01:author_add' %}>添加作者</a>
          <div class="table-responsive">
            <table class="table table-striped table-hover">
                <thead>
                    <tr>
                        <th>序号</th>
                        <th>ID</th>
                        <th>作者</th>
                        <th>代表作</th>
                        <th>操作</th>
                    </tr>
                </thead>
                <tbody>
                    {% for author in all_authors %}
                        <tr>
                            <td>{{ forloop.counter }}</td>
                            <td>{{ author.pk }}</td>
                            <td>{{ author.name }}</td>
{# pub对象定义了__str__方法#}
                            <td>
{#                                {% for book in author.books.all %}#}
{#                                    《 {{ book.title }} 》#}
{#                                {% endfor %}#}
                                {{ author.show_books }}
                            </td>
                            <td><a class="btn btn-danger btn-sm" href={% url 'app01:del' 'author' author.pk %}>删除</a></td>
                            <td><a class="btn btn-primary btn-sm" href={% url 'app01:author_edit' author.pk %}>编辑</a></td>
                        </tr>
                    {% endfor %}
               </tbody>

            </table>
          </div>

{% endblock %}

templates/author_add.html
{% extends 'base.html' %}

{% block title %}
    author_book
{% endblock %}

{% block author_active %}
    active
{% endblock %}

{% block content %}

    <form class="form-horizontal" method="post" action="">
    {% csrf_token %}
      <div class="form-group">
        <label for="author_name" class="col-sm-2 control-label">作者名</label>
        <div class="col-sm-8">
          <input type="text" class="form-control" id="author_name" name="author_name">
            <span style="color:red">{{ error }}</span>
        </div>
      </div>
      <div class="form-group">
        <label for="works" class="col-sm-2 control-label">代表作</label>
        <div class="col-sm-8">
            <select name="book_id" id="works" class="form-control" multiple>
                {% for book in all_books %}
                    <option value="{{ book.pk }}">{{ book.title }}</option>
                {% endfor %}
            </select>
        </div>
      </div>
      <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
          <button type="submit" class="btn btn-default">保存</button>
        </div>
      </div>
    </form>



{#    <form action="" method="post">#}
{#        {% csrf_token %}#}
{#        <p>#}
{#            作者名: <input type="text" name="author_name">#}
{#            <span>{{ error }}</span>#}
{#        </p>#}
{#        <p>#}
{#            代表作:#}
{#            <select name="book_id" id="" multiple>#}
{#                {% for book in all_books %}#}
{#                    <option value="{{ book.pk }}">{{ book.title }}</option>#}
{#                {% endfor %}#}
{#            </select>#}
{##}
{#        </p>#}
{#        <p>#}
{#            <button>提交</button>#}
{#        </p>#}
{#    </form>#}

{% endblock %}

templates/author_edit.html
{% extends 'base.html' %}

{% block title %}
    author_edit
{% endblock %}

{% block author_active %}
    active
{% endblock %}

{% block content %}

<form class="form-horizontal" method="post" action="">
{% csrf_token %}
  <div class="form-group">
    <label for="author_name" class="col-sm-2 control-label">作者名</label>
    <div class="col-sm-8">
      <input type="text" name="author_name" class="form-control" id="author_name" value="{{ author_obj.name }}">
        <span style="color:red">{{ error }}</span>
    </div>
  </div>
  <div class="form-group">
    <label for="works" class="col-sm-2 control-label">代表作</label>
    <div class="col-sm-8">
        <select name="book_id" id="" class="form-control" multiple>
            {% for book in all_books %}
                {% if book in author_obj.books.all %}
                    <option selected value="{{ book.pk }}">{{ book.title }}</option>
                {% else %}
                    <option value="{{ book.pk }}">{{ book.title }}</option>

                {% endif %}

            {% endfor %}
        </select>
    </div>
  </div>

  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <button type="submit" class="btn btn-default">保存</button>
    </div>
  </div>
</form>


{#    <form action="" method="post">#}
{#        {% csrf_token %}#}
{#        <p>#}
{#            作者名: <input type="text" name="author_name" value="{{ author_obj.name }}">#}
{#            <span>{{ error }}</span>#}
{#        </p>#}
{#        <p>#}
{#            代表作:#}
{#            <select name="book_id" id="" multiple>#}
{#                {% for book in all_books %}#}
{#                    {% if book in author_obj.books.all %}#}
{#                        <option selected value="{{ book.pk }}">{{ book.title }}</option>#}
{#                    {% else %}#}
{#                        <option value="{{ book.pk }}">{{ book.title }}</option>#}
{#                    {% endif %}#}
{#                {% endfor %}#}
{#            </select>#}
{##}
{#        </p>#}
{#        <p>#}
{#            <button>提交</button>#}
{#        </p>#}
{#    </form>#}

{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}

        {% endblock %}

    </title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'plugins/bootstrap-3.3.7-dist/css/bootstrap.css'%}">
    <link rel="stylesheet" href="{% static 'css/dashboard.css' %}">
{#    <link rel="stylesheet" href="/static/plugins/bootstrap-3.3.7-dist/css/bootstrap.css">#}
{#    <link rel="stylesheet" href="/static/css/dashboard.css">#}
    <style>
        * {
            font-family:"微软雅黑";
        }
    </style>

</head>

<body>

    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">图书管理系统</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
            <li><a href="#">Dashboard</a></li>
            <li><a href="#">Settings</a></li>
            <li><a href="#">Profile</a></li>
            <li><a href="#">Help</a></li>
          </ul>
          <form class="navbar-form navbar-right">
            <input type="text" class="form-control" placeholder="Search...">
          </form>
        </div>
      </div>
    </nav>

    <div class="container-fluid">
      <div class="row">
        <div class="col-sm-3 col-md-2 sidebar">
          <ul class="nav nav-sidebar">
            <li class="{% block pub_active%} {% endblock %}"><a href="{% url 'app01:publisher' %}">出版社列表 <span class="sr-only">(current)</span></a></li>
            <li class="{% block book_active%} {% endblock %}"><a href="{% url 'app01:book' %}">书籍列表</a></li>
            <li class="{% block author_active%} {% endblock %}"><a href="{% url 'app01:author' %}">作者列表</a></li>
{#            <li><a href="#">Export</a></li>#}
          </ul>
        </div>
        <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">

            {% block content %}

            {% endblock %}



        </div>
      </div>
    </div>

</body>


</html>

templates/book_add.html
{% extends 'base.html' %}

{% block title %}
    add_book
{% endblock %}

{% block book_active %}
    active
{% endblock %}

{% block content %}
    <form class="form-horizontal" action="" method="post">
    {% csrf_token %}
      <div class="form-group">
        <label for="book_name" class="col-sm-2 control-label">书名</label>
        <div class="col-sm-8">
          <input type="text" name="title" class="form-control" id="book_name">
            <span style="color:red">{{ error }}</span>
        </div>
      </div>
      <div class="form-group">
        <label for="pub_id" class="col-sm-2 control-label">出版社</label>
        <div class="col-sm-8">
            <select name="pub_id" id="pub_id" class="form-control">
                {% for pub in all_pubs %}
                    <option value="{{ pub.pk }}">{{ pub.name }}</option>
                {% endfor %}
            </select>

        </div>
      </div>

      <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
          <button type="submit" class="btn btn-default">保存</button>
        </div>
      </div>
    </form>



{#    <form action="" method="post">#}
{#        {% csrf_token %}#}
{#        <p>#}
{#            书名: <input type="text" name="title">#}
{#            <span>{{ error }}</span>#}
{#        </p>#}
{#        <p>#}
{#            出版社:#}
{#            <select name="pub_id" id="">#}
{#                {% for pub in all_pubs %}#}
{#                    <option value="{{ pub.pk }}">{{ pub.name }}</option>#}
{#                {% endfor %}#}
{#            </select>#}
{##}
{#        </p>#}
{#        <p>#}
{#            <button>提交</button>#}
{#        </p>#}
{#    </form>#}

{% endblock %}

templates/book_edit.html
{% extends 'base.html' %}

{% block title %}
    book_edit
{% endblock %}

{% block book_active %}
    active
{% endblock %}

{% block content %}
    <form class="form-horizontal" method="post" action="">
    {% csrf_token %}
      <div class="form-group">
        <label for="book_name" class="col-sm-2 control-label">书名</label>
        <div class="col-sm-8">
          <input type="text" class="form-control" id="book_name" name="title" value="{{ book_obj.title }}">
            <span style="color:red">{{ error }}</span>
        </div>
      </div>
      <div class="form-group">
        <label for="pub_name" class="col-sm-2 control-label">出版社</label>
        <div class="col-sm-8">
            <select name="pub_id" id="pub_name" class="form-control">
                {% for pub in all_pubs %}
                    {% if book_obj.pub == pub %}
                    <option selected value="{{ pub.pk }}">{{ pub.name }}</option>
                    {% else %}
                    <option value="{{ pub.pk }}">{{ pub.name }}</option>
                    {% endif %}
                {% endfor %}
            </select>
        </div>
      </div>

      <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
          <button type="submit" class="btn btn-default">保存</button>
        </div>
      </div>
    </form>






{#    <form action="" method="post">#}
{#        {% csrf_token %}#}
{#        <p>#}
{#            书名: <input type="text" name="title" value="{{ book_obj.title }}">#}
{#            <span>{{ error }}</span>#}
{#        </p>#}
{#        <p>#}
{#            出版社:#}
{#            <select name="pub_id" id="">#}
{#                {% for pub in all_pubs %}#}
{#                    方式1： #}
{#                    {% if book_obj.pub == pub %}#}
{#                        <option selected value="{{ pub.pk }}">{{ pub.name }}</option>#}
{#                    {% else %}#}
{#                        <option value="{{ pub.pk }}">{{ pub.name }}</option>#}
{#                    {% endif %}#}
{##}
{#                    <option {{{% if book_obj.pub == pub %} selected {% endif %} value="{{ pub.pk }}">{{ pub.name }}}}</option>#}
{##}
{##}
{##}
{#                {% endfor %}#}
{#            </select>#}
{##}
{#        </p>#}
{#        <p>#}
{#            <button>提交</button>#}
{#        </p>#}
{#    </form>#}

{% endblock %}

templates/book_list.html
{% extends 'base.html' %}

{% block title %}
   book
{% endblock %}

{% block book_active %}
    active
{% endblock %}

{% block content %}

          <h2 class="sub-header">书籍列表</h2>
            <a class="btn btn-info btn-default" href={% url 'app01:book_add' %}>添加书籍</a>
          <div class="table-responsive">
            <table class="table table-striped table-hover">
                <thead>
                    <tr>
                        <th>序号</th>
                        <th>ID</th>
                        <th>书籍名称</th>
                        <th>出版社</th>
                        <th>操作</th>
                    </tr>
                </thead>
                <tbody>
                    {% for book in books %}
                        <tr>
                            <td>{{ forloop.counter }}</td>
                            <td>{{ book.id }}</td>
                            <td>{{ book.title }}</td>
{# pub对象定义了__str__方法#}
                            <td>{{ book.pub }}</td>
                            <td><a class="btn btn-danger btn-sm" href={% url 'app01:del' 'book' book.pk %}>删除</a></td>
                            <td><a class="btn btn-primary btn-sm" href={% url 'app01:book_edit' book.pk %}>编辑</a></td>
                        </tr>
                    {% endfor %}
               </tbody>

            </table>
          </div>

{% endblock %}

templates/publisher_add.html
{% extends 'base.html' %}

{% block title %}
    publisher_edit
{% endblock %}

{% block pub_active %}
    active
{% endblock %}

{% block content %}
    <form class="form-horizontal" method="post" action="">
        {% csrf_token %}
          <div class="form-group">
            <label for="pub_name" class="col-sm-2 control-label">出版社名称</label>
                <div class="col-sm-6">
                  <input type="text" class="form-control" id="pub_name" name="pub_name">
                    <span style="color:red">{{ error }}</span>
                </div>
          </div>
          <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
              <button type="submit" class="btn btn-default">保存</button>
            </div>
          </div>
    </form>



{#    <form action="" method="post">#}
{#        {% csrf_token %}#}
{#        <p>#}
{#            出版社名称: <input type="text" name="pub_name">#}
{#            <span>{{ error }}</span>#}
{#        </p>#}
{#        <p>#}
{#            <button>提交</button>#}
{#        </p>#}
{#    </form>#}

{% endblock %}

templates/publisher_edit.html
{% extends 'base.html' %}

{% block title %}
    publisher_edit
{% endblock %}

{% block pub_active %}
    active
{% endblock %}

{% block content %}
    <form class="form-horizontal" method="post" action="">
    {% csrf_token %}
      <div class="form-group">
        <label for="pub_name" class="col-sm-2 control-label">出版社名称</label>
            <div class="col-sm-6">
              <input type="text" class="form-control" id="pub_name" name="pub_name" value="{{ obj.name }}">
                <span>{{ error }}</span>
            </div>
      </div>
      <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
          <button type="submit" class="btn btn-default">保存</button>
        </div>
      </div>
    </form>

{#<form action="" method="post">#}
{#    {% csrf_token %}#}
{#    <p>#}
{#        出版社名称: <input type="text" name="pub_name" value="{{ obj.name }}">#}
{#        <span>{{ error }}</span>#}
{#    </p>#}
{#    <p>#}
{#        <button>提交</button>#}
{#    </p>#}
{#</form>#}

{% endblock %}

templates/publisher_list.html
{% extends 'base.html' %}

{% block title %}
    publisher
{% endblock %}

{% block pub_active %}
   active
{% endblock %}

{% block content %}

          <h2 class="sub-header">出版社列表</h2>
            <a class="btn btn-info btn-default" href={% url 'app01:pub_add' %}>添加出版社</a>
          <div class="table-responsive">
            <table class="table table-striped table-hover">
                <thead>
                    <tr>
                        <th>序号</th>
                        <th>ID</th>
                        <th>出版社名字</th>
                        <th>操作</th>
                    </tr>
                </thead>
                <tbody>
                    {% for publisher in all_pubs %}
                        <tr>
                            <td>{{ forloop.counter }}</td>
                            <td>{{ publisher.id }}</td>
                            <td>{{ publisher.name }}</td>
                            <td><a class="btn btn-danger btn-sm" href={% url 'app01:del' 'publisher' publisher.id %}>删除</a></td>
                            <td><a class="btn btn-primary btn-sm" href={% url 'app01:pub_edit' id=publisher.id %}>编辑</a></td>
                        </tr>
                    {% endfor %}
               </tbody>

            </table>
          </div>

{% endblock %}